# Generated by Django 5.2.16 on 2026-07-16 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time to complete the whole module.')),
                ('order_index', models.PositiveIntegerField(help_text='Position in the sequential unlock order (1-6).', unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Unpublishing is our soft delete — never hard-delete a module, it would orphan historical quiz results.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(help_text='Order within the module.')),
                ('title', models.CharField(max_length=255)),
                ('body_text', models.TextField(help_text='TinyMCE HTML. MUST be sanitised on save — it renders unescaped.')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, help_text='Used by the adaptive feedback engine to estimate revision time.')),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='modules.module')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['module__order_index', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='modules.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_records',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_text', models.TextField(help_text='The opening scenario shown to the learner.')),
                ('decision_points', models.JSONField(default=dict, help_text='Branching decision tree.')),
                ('outcome_text', models.JSONField(default=dict, help_text="Outcomes keyed by decision path. JSON, not text: the spec describes one field holding 'each possible outcome', which a single text field cannot represent.")),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='modules.module')),
            ],
            options={
                'db_table': 'simulations',
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'lesson_number'), name='unique_lesson_number_per_module'),
        ),
        migrations.AddConstraint(
            model_name='progressrecord',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_progress_per_user_lesson'),
        ),
    ]
