# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text="Correct decisions, out of the scenario's total.")),
                ('total', models.PositiveIntegerField(default=0, help_text='Decisions available in the scenario.')),
                ('path', models.JSONField(blank=True, default=list, help_text='The decisions the student made.')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='modules.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulation_results',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'simulation'), name='unique_simulation_per_user')],
            },
        ),
    ]
