# Generated by Django 5.2.16 on 2026-07-29 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_simulationresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('task_key', models.CharField(help_text='Stable id within the lesson (for progress rows).', max_length=80)),
                ('kind', models.CharField(choices=[('CONCEPT', 'Concept'), ('CHECK', 'Check question'), ('SCENARIO', 'Scenario')], default='CONCEPT', max_length=20)),
                ('points', models.PositiveIntegerField(default=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, help_text='Teaching HTML (sanitised on save).')),
                ('diagram_key', models.CharField(blank=True, help_text='Names a CSS/SVG diagram partial.', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='For check/scenario tasks: scenario, question and options [{text, correct, explanation}].')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='modules.lesson')),
            ],
            options={
                'db_table': 'lesson_tasks',
                'ordering': ['lesson__module__order_index', 'lesson__lesson_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='modules.lessontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_progress',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lessontask',
            constraint=models.UniqueConstraint(fields=('lesson', 'task_key'), name='unique_task_key_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='taskprogress',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_task_progress_per_user'),
        ),
    ]
