# Generated by Django 5.2.16 on 2026-07-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_lessontask_taskprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontask',
            name='kind',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('CHECK', 'Check question'), ('SCENARIO', 'Scenario'), ('SORT', 'Sort into buckets'), ('INBOX', 'Inspect an inbox'), ('SPOT', 'Spot the fake'), ('PASSWORD', 'Password builder'), ('BRANCH', 'Branching scenario')], default='CONCEPT', max_length=20),
        ),
    ]
