# Generated by Django 5.2.16 on 2026-07-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_lessontask_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontask',
            name='kind',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('CHECK', 'Check question'), ('SCENARIO', 'Scenario'), ('SORT', 'Sort into buckets'), ('INBOX', 'Inspect an inbox'), ('SPOT', 'Spot the fake'), ('PASSWORD', 'Password builder'), ('BRANCH', 'Branching scenario'), ('CLASSIFY', 'Classify each alert'), ('MAILSORT', 'Triage a mixed inbox'), ('HARDEN', 'Secure a workspace')], default='CONCEPT', max_length=20),
        ),
    ]
