# Generated by Django 5.2.16 on 2026-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_lessontask_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='admin_edited',
            field=models.BooleanField(default=False, help_text='An admin has edited this lesson in the console. The seed leaves such rows alone (unless run with --force).'),
        ),
        migrations.AddField(
            model_name='module',
            name='admin_edited',
            field=models.BooleanField(default=False, help_text="An admin has edited this module's content in the console. The seed leaves such rows alone (unless run with --force) so a reseed can't silently wipe the edit."),
        ),
    ]
