# Generated by Django 5.2.16 on 2026-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_lessontask_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontask',
            name='image',
            field=models.JSONField(blank=True, default=dict, help_text='Optional real photo served from our own static (CSP-safe): {src, alt, caption, credit}. Rendered via _lesson_image.html.'),
        ),
    ]
