# Generated by Django 5.2.16 on 2026-08-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_lessontask_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short motto/framing line shown on the module overview.', max_length=120),
        ),
    ]
