# Generated by Django 5.2.16 on 2026-08-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_module_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontask',
            name='kind',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('CHECK', 'Check question'), ('SCENARIO', 'Scenario'), ('SORT', 'Sort into buckets'), ('INBOX', 'Inspect an inbox'), ('SPOT', 'Spot the fake'), ('PASSWORD', 'Password builder'), ('BRANCH', 'Branching scenario'), ('CLASSIFY', 'Classify each alert'), ('MAILSORT', 'Triage a mixed inbox'), ('HARDEN', 'Secure a workspace'), ('NETMAP', 'Find network weaknesses'), ('SEQUENCE', 'Order the steps'), ('RESPOND', 'Respond to situations'), ('QUIZSET', 'Mixed question set'), ('FIREWALL', 'Read the firewall rules'), ('TABLETOP', 'Incident tabletop')], default='CONCEPT', max_length=20),
        ),
    ]
