# Generated by Django 5.2.16 on 2026-08-06 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add_user', 'Added a user'), ('role_change', 'Changed a role'), ('deactivate', 'Deactivated an account'), ('activate', 'Activated an account'), ('resend_verification', 'Resent verification'), ('nudge', 'Sent a nudge'), ('flag', 'Flagged a learner'), ('unflag', 'Cleared a flag'), ('publish', 'Published content'), ('unpublish', 'Unpublished content')], max_length=32)),
                ('summary', models.CharField(help_text='A human-readable description of the action.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
