# Generated by Django 5.2.16 on 2026-08-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('add_user', 'Added a user'), ('role_change', 'Changed a role'), ('deactivate', 'Deactivated an account'), ('activate', 'Activated an account'), ('resend_verification', 'Resent verification'), ('nudge', 'Sent a nudge'), ('flag', 'Flagged a learner'), ('unflag', 'Cleared a flag'), ('publish', 'Published content'), ('unpublish', 'Unpublished content'), ('publish_lesson', 'Published a lesson'), ('unpublish_lesson', 'Unpublished a lesson'), ('edit_module', 'Edited a module'), ('edit_lesson', 'Edited a lesson'), ('edit_question', 'Edited a quiz question')], max_length=32),
        ),
    ]
