# Generated by Django 5.2.16 on 2026-08-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_adminaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('add_user', 'Added a user'), ('role_change', 'Changed a role'), ('deactivate', 'Deactivated an account'), ('activate', 'Activated an account'), ('resend_verification', 'Resent verification'), ('nudge', 'Sent a nudge'), ('flag', 'Flagged a learner'), ('unflag', 'Cleared a flag'), ('publish', 'Published content'), ('unpublish', 'Unpublished content'), ('publish_lesson', 'Published a lesson'), ('unpublish_lesson', 'Unpublished a lesson'), ('edit_module', 'Edited a module'), ('edit_lesson', 'Edited a lesson'), ('edit_question', 'Edited a quiz question'), ('create_org', 'Created an organisation'), ('edit_org', 'Edited an organisation'), ('delete_org', 'Deleted an organisation'), ('assign_org', "Changed a learner's organisation"), ('note_org', 'Sent a note to an organisation'), ('note_user', 'Sent a note to a learner')], max_length=32),
        ),
    ]
