# Generated by Django 5.2.16 on 2026-09-05 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_adminaction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('add_user', 'Added a user'), ('role_change', 'Changed a role'), ('deactivate', 'Deactivated an account'), ('activate', 'Activated an account'), ('resend_verification', 'Resent verification'), ('nudge', 'Sent a nudge'), ('flag', 'Flagged a learner'), ('unflag', 'Cleared a flag'), ('publish', 'Published content'), ('unpublish', 'Unpublished content'), ('publish_lesson', 'Published a lesson'), ('unpublish_lesson', 'Unpublished a lesson'), ('edit_module', 'Edited a module'), ('edit_lesson', 'Edited a lesson'), ('edit_question', 'Edited a quiz question'), ('create_org', 'Created an organisation'), ('edit_org', 'Edited an organisation'), ('delete_org', 'Deleted an organisation'), ('assign_org', "Changed a learner's organisation"), ('note_org', 'Sent a note to an organisation'), ('note_user', 'Sent a note to a learner'), ('add_note', 'Added a private note'), ('reset_quiz', 'Reset a quiz attempt'), ('reset_progress', 'Reset course progress'), ('bulk_action', 'Ran a bulk action'), ('bulk_invite', 'Bulk-invited users'), ('revoke_cert', 'Revoked a certificate'), ('set_due', 'Set a training due date'), ('password_reset', 'Sent a password reset')], max_length=32),
        ),
        migrations.CreateModel(
            name='LearnerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learner_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
