# Generated by Django 5.2.16 on 2026-08-30 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_serial_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal verification identifier.', unique=True),
        ),
    ]
