# Generated by Django 5.2.16 on 2026-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Set when an administrator revokes this certificate. A revoked certificate fails public verification.', null=True),
        ),
    ]
