# Generated by Django 5.2.16 on 2026-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Marked by an administrator as needing attention (e.g. the learner has fallen behind).'),
        ),
    ]
