# Generated by Django 5.2.16 on 2026-08-10 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_flag_reason_userprofile_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sector', models.CharField(blank=True, help_text='e.g. Local council, School, Small business, Not-for-profit.', max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org',
            field=models.ForeignKey(blank=True, help_text="Canonical organisation link. The `organisation` text field mirrors this record's name.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='authentication.organisation'),
        ),
    ]
