# Generated by Django 5.2.16 on 2026-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_backfill_organisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='celebrated_tier',
            field=models.PositiveSmallIntegerField(default=0, help_text='Highest tier index the student has already been congratulated for. The dashboard fires a one-time celebration when they climb past it.'),
        ),
    ]
