# Generated by Django 5.2.16 on 2026-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_backfill_celebrated_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='console_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text="An administrator's remembered light/dark choice for the console.", max_length=5),
        ),
    ]
