# Generated by Django 5.2.16 on 2026-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_console_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='training_due',
            field=models.DateField(blank=True, help_text="The date this organisation's staff are expected to have completed training by. Drives the overdue and compliance reporting.", null=True),
        ),
    ]
