# Generated by Django 5.2.16 on 2026-07-16 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('lesson_reference', models.ForeignKey(help_text="The lesson that teaches this question's topic.", on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='modules.lesson')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('correct_answer', models.BooleanField(default=False)),
                ('explanation_text', models.TextField(help_text='Why this option is right or wrong. Shown to the learner when they choose incorrectly.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('pass_mark', models.PositiveIntegerField(default=70, help_text='Percentage required to pass.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='modules.module')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Percentage.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_results',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.ForeignKey(help_text='The option they should have picked.', on_delete=django.db.models.deletion.CASCADE, related_name='missed_in', to='quizzes.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='quizzes.question')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='quizzes.quizresult')),
                ('student_answer', models.ForeignKey(help_text='The option the student picked.', on_delete=django.db.models.deletion.CASCADE, related_name='chosen_wrongly_in', to='quizzes.answer')),
            ],
            options={
                'db_table': 'wrong_answers',
            },
        ),
        migrations.AddConstraint(
            model_name='quizresult',
            constraint=models.UniqueConstraint(fields=('user', 'quiz', 'attempt_number'), name='unique_attempt_number_per_user_quiz'),
        ),
        migrations.AddConstraint(
            model_name='wronganswer',
            constraint=models.UniqueConstraint(fields=('quiz_result', 'question'), name='unique_wrong_answer_per_question_per_attempt'),
        ),
    ]
