# Generated by Django 5.2.16 on 2026-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_edited',
            field=models.BooleanField(default=False, help_text='An admin has edited this question (or its answers) in the console. The seed leaves such rows alone (unless run with --force).'),
        ),
    ]
